import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import FabActionButton from "./components/FabActionButton";

export const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang='en'>
          <body className={inter.className}>
              <Header />
              {children}
              <FabActionButton />
          </body>
      </html>
  );
}
